### PR TITLE
New maintenance template

### PR DESCRIPTION
**Pull request by mitovskaol**
Added a new template to be used for maintenance announcements in the Rocket.Chat #devops-alerts channel.

### CODE REVIEW

**Comment by sbarre-esit** [comment]
Looks good to me. I'd like to get @wmhutchison and @tbaker1313 input tomorrow (they are both flexing today)

**Comment by juhewitt** [comment]
Awaiting @wmhutchison  and @tbaker1313, I'm good.

**Comment by wmhutchison** [comment]
I'm fine with this format

**Comment by tbaker1313** [comment]
Looks fine to me as well.

**Pull request merged**
