### PR TITLE
Dmz firewall

### PR DESCRIPTION
**Pull request by sbarre-esit**

### CODE REVIEW

**Comment by jefkel** [comment]
Is there a reason that you're removing old notices in this PR rather than just adding a new (current) one?

**Comment by stewartshea** [comment]
Ultimately I'd say it doesn't really matter either way. Removing them keeps
the dashboard scrolldown a little more clean, but we also have the commit
history if we need to look back in time.
A future enhancement could be to simply display the last 5 notices or
something like that, but that would be a low priority feature IMO
--
Shea Stewart, Partner
Arctiq: Intelligent Architecture
shea.stewart@arctiq.ca
+1-647-972-5191
http://www.arctiq.ca

**Comment by sbarre-esit** [comment]
Ya, I was removing expired ones so they don't show up on the status page.

**Comment by sbarre-esit** [comment]
Closing PR to re-open to retest #10 codeowners fix

**Pull request closed without merging**
